export default function (appContext) {
  return {
    category: [
      {
        text: "all_caps",
        value: 0,
        category_id: 0,
        selected: true,
      },
      {
        text: "general_info_caps",
        value: 0,
        category_id: 1,
        selected: false,
      },
      {
        text: "user_info_caps",
        value: 0,
        category_id: 2,
        selected: false,
      },
      {
        text: "location_caps",
        value: 0,
        category_id: 3,
        selected: false,
      },
      {
        text: "datewise_caps",
        value: 0,
        category_id: 4,
        selected: false,
      },
    ],
    // breadcrumb
    breadcrumb: [
      { text: "dashboard", exact: true, to: "/" },
      {
        text: "job_posts",
        disabled: true,
        to: "/users",
        icon: "mdi-earth",
      },
    ],

    // tab items
    tabItems: [
      {
        text: "all",
        icon: "fa-table",
        isSelected: 1,
        key: "all",
      },
      {
        text: "active",
        icon: "fa-thumbs-up",
        isSelected: 0,
        key: "active",
      },
      {
        text: "completed",
        icon: "fa-check",
        isSelected: 0,
        key: "completed",
      },
      {
        text: "cancelled",
        icon: "fa-exclamation-circle",
        isSelected: 0,
        key: "cancelled",
      },
      {
        text: "onhold",
        icon: "fa-user-slash",
        isSelected: 0,
        key: "onhold",
      },
      {
        text: "expired",
        icon: "fa-exclamation-triangle",
        isSelected: 0,
        key: "expired",
      },
      {
        text: "removed",
        icon: "fa-trash",
        isSelected: 0,
        key: "removed",
      },
    ],

    // table headers
    headers: [
      {
        text: "id",
        value: "code",
        select: false,
        id: 1,
        category_id: 1,
        sortable: false,
      },
      {
        text: "reference",
        value: "reference",
        select: false,
        id: 2,
        category_id: 1,
      },
      {
        text: "occupation",
        value: "occupation_id",
        select: false,
        id: 3,
        category_id: 1,
      },
      {
        text: "is_remote",
        value: "is_remote",
        select: false,
        id: 4,
        category_id: 1,
      },
      {
        text: "headcount",
        value: "headcount",
        select: false,
        id: 5,
        category_id: 1,
      },
      {
        text: "status",
        value: "status",
        select: false,
        id: 6,
        category_id: 1,
      },
      {
        text: "salary_type",
        value: "salary_type",
        select: false,
        id: 7,
        category_id: 1,
        sortable: false,
      },
      {
        text: "min_salary",
        value: "min_salary",
        select: false,
        id: 8,
        category_id: 1,
      },
      {
        text: "max_salary",
        value: "max_salary",
        select: false,
        id: 9,
        category_id: 1,
      },
      {
        text: "contract_type",
        value: "contract_type",
        select: false,
        id: 36,
        category_id: 1,
      },
      {
        text: "office_address",
        value: "office_address",
        select: false,
        id: 10,
        category_id: 1,
      },
      {
        text: "minimum_experience_level",
        value: "minimum_experience_level",
        select: false,
        id: 11,
        category_id: 1,
        sortable: false,
      },
      {
        text: "open_date",
        value: "open_date",
        select: false,
        id: 12,
        category_id: 1,
        sortable: false,
      },
      {
        text: "close_date",
        value: "close_date",
        select: false,
        id: 12,
        category_id: 1,
        sortable: false,
      },
      {
        text: "expected_close_date",
        value: "expected_close_date",
        select: false,
        id: 13,
        category_id: 1,
        sortable: false,
      },
      {
        text: "descriptions",
        value: "descriptions",
        select: false,
        id: 14,
        category_id: 1,
        sortable: false,
      },
      {
        text: "details",
        value: "details",
        select: false,
        id: 15,
        category_id: 1,
        sortable: false,
      },
      {
        text: "number_of_views",
        value: "number_of_views",
        select: false,
        id: 16,
        category_id: 1,
        sortable: false,
      },
      {
        text: "is_published",
        value: "is_published",
        select: false,
        id: 17,
        category_id: 1,
      },
      {
        text: "published_link",
        value: "published_link",
        select: false,
        id: 18,
        category_id: 1,
        sortable: false,
      },
      {
        text: "first_published_at",
        value: "first_published_at",
        select: false,
        id: 19,
        category_id: 1,
      },
      {
        text: "last_published_at",
        value: "last_published_at",
        select: false,
        id: 20,
        category_id: 1,
      },
      {
        text: "is_pinned",
        value: "is_pinned",
        select: false,
        id: 21,
        category_id: 1,
      },
      {
        text: "source",
        value: "source",
        select: false,
        id: 22,
        category_id: 1,
        sortable: false,
      },
      {
        text: "location",
        value: "location",
        select: false,
        id: 23,
        category_id: 1,
        sortable: false,
      },
      {
        text: "department",
        value: "department_id",
        select: false,
        id: 24,
        category_id: 1,
        sortable: false,
      },
      {
        text: "created_by",
        value: "created_by",
        select: false,
        id: 25,
        category_id: 1,
      },
      {
        text: "updated_by",
        value: "updated_by",
        select: false,
        id: 26,
        category_id: 1,
      },
      {
        text: "deleted_at",
        value: "deleted_at",
        select: false,
        id: 27,
        category_id: 1,
      },
      {
        text: "created_at",
        value: "created_at",
        select: false,
        id: 28,
        category_id: 1,
      },
      {
        text: "updated_at",
        value: "updated_at",
        select: false,
        id: 29,
        category_id: 1,
      },
    ],
  };
}
