export default [
  {
    logo: "/icons/SYSTEM ICON/System Icone-06.svg",
    color: "red",
    text: "File Management System",
    key: "file_management_system",
    items: [
      // {
      //   key: 'menu.unreads',
      //   text: 'All Unread',
      //   icon: 'mdi-message-badge',
      //   link: '/file_management/unreads',
      //   exact: true,
      //   scope: 'Unreads-View',
      // },
      // {
      //   icon: 'mdi-clock-time-four',
      //   key: 'menu.recent',
      //   text: 'Recent',
      //   link: '/file_management/recent',
      //   exact: true,
      //   scope: 'Recent-View',
      // },
      // {
      //   icon: 'mdi-star',
      //   key: 'menu.favorites',
      //   text: 'Favorites',
      //   link: '/file_management/favorites',
      //   exact: true,
      //   scope: 'Favorites-View',
      // },

      // {
      //   icon: 'mdi-label',
      //   key: 'menu.labels',
      //   text: 'Labels',
      //   link: '/file_management/labels',
      //   exact: true,
      //   scope: 'Labels-View',
      // },
      // {
      //   icon: 'mdi-folder',
      //   key: 'menu.folders',
      //   text: 'Folders',
      //   link: '/file_management/folders',
      //   exact: true,
      //   scope: 'Folders-View',
      // },
      // {
      //   icon: 'mdi-folder-download',
      //   key: 'menu.shared',
      //   text: 'Shared',
      //   link: '/file_management/shared',
      //   exact: true,
      //   scope: 'Shared-View',
      // },
      // {
      //   icon: 'mdi-folder-plus',
      //   key: 'menu.collect',
      //   text: 'Collect',
      //   link: '/file_management/collect',
      //   exact: true,
      //   scope: 'Collect-View',
      // },
      // {
      //   icon: 'mdi-delete',
      //   key: 'menu.trash',
      //   text: 'Trash',
      //   link: '/file_management/trash',
      //   exact: true,
      //   scope: 'Collect-View',
      // },
      {
        icon: "mdi-camera-image",
        key: "system_file_manager",
        text: "System File Manager",
        scope: [
          "user_management_system-view",
          "supplier_management_system-view",
          "content_management_system-view",
          "designer_management_system-view",
        ],
        items: [
          {
            icon: "mdi-image-multiple",
            key: "user_management_system",
            text: "UserManagementSystem",
            link: "/file_management/user_management",
            exact: true,
            scope: "user_management_system-view",
          },
          {
            icon: "mdi-badge-account-horizontal",
            key: "supplier_management_system",
            text: "SupplierManagementSystem",
            link: "/file_management/supplier_management",
            exact: true,
            scope: "supplier_management_system-view",
          },
          {
            icon: "mdi-application",
            key: "content_management_system",
            text: "ContentManagementSystem",
            link: "/file_management/content_management",
            exact: true,
            scope: "content_management_system-view",
          },
          {
            icon: "mdi-card-account-details-star",
            key: "designer_management_system",
            text: "DesignerManagementSystem",
            link: "/file_management/designer_management",
            exact: true,
            scope: "designer_management_system-view",
          },
        ],
      },
    ],
  },
];
