export default [
  {
    logo: '/icons/SYSTEM ICON/System Icone-01.svg',
    color: 'primary',
    text: 'Master Management System',
    key: 'master_management_system',
    items: [
      {
        icon: 'mdi-earth',
        key: 'countries',
        text: 'Countries List',
        link: '/masters/countries',
        exact: true,
        scope: 'countries-view',
      },

      {
        icon: 'mdi-school',
        key: 'departments',
        text: 'Departments List',
        link: '/masters/departments',
        exact: true,
        scope: 'departments-view',
      },
      {
        icon: 'mdi-domain',
        key: 'companies',
        text: 'Companies List',
        link: '/masters/companies',
        exact: true,
        scope: 'companies-view',
      },

      {
        icon: 'mdi-cogs',
        key: 'systems',
        text: 'Systems List',
        link: '/masters/systems',
        exact: true,
        scope: 'systems-view',
      },
      {
        icon: 'mdi-map-marker-radius',
        key: 'business_locations',
        text: 'Business Location',
        link: '/masters/businessLocations',
        exact: true,
        scope: 'business_locations-view',
      },
      {
        icon: 'mdi-cog',
        key: 'language_setting',
        text: 'Language Setting',
        scope: ['languages-view'],
        items: [
          {
            icon: 'mdi-earth',
            key: 'languages',
            text: 'Languages',
            link: '/languages',
            exact: true,
            scope: 'languages-view',
          },
          {
            icon: 'fa-globe',
            key: 'translation',
            text: 'Languages',
            link: '/languages/translation',
            exact: true,
            scope: 'languages-view',
          },
        ],
      },

      {
        icon: 'mdi-cog',
        key: 'settings',
        text: 'Settings',
        scope: ['labels-view'],
        items: [
          {
            icon: 'mdi-svg',
            key: 'status_event_list',
            text: 'Status Event List',
            link: '/status_management/status_event/master',
            exact: true,
            scope: 'reasons-view',
          },
          {
            icon: 'mdi-head-question',
            key: 'reason_list',
            text: 'Reasons List',
            link: '/status_management/reasons/master',
            exact: true,
            scope: 'reasons-view',
          },
          {
            icon: 'mdi-shuffle',
            key: 'labels',
            text: 'Labels List',
            link: '/labels/master',
            exact: true,
            scope: 'labels-view',
          },
        ],
      },
      {
        icon: 'mdi-account-details',
        key: 'master_activity',
        text: 'Activities List',
        link: '/masters/logs',
        exact: true,
        scope: 'user_activity-view',
      },
      {
        icon: 'fa-icons',
        key: 'socialMedia',
        text: 'Social Media List',
        link: '/masters/social-media',
        exact: true,
        scope: 'social_media-view',
      },
    ],
  },
];
