export default function (appContext) {
  return {
    category: [
      {
        text: "all_caps",
        value: 0,
        category_id: 0,
        selected: true,
      },
      {
        text: "general_info_caps",
        value: 0,
        category_id: 1,
        selected: false,
      },
      {
        text: "user_info_caps",
        value: 0,
        category_id: 2,
        selected: false,
      },
      {
        text: "location_caps",
        value: 0,
        category_id: 3,
        selected: false,
      },
      {
        text: "datewise_caps",
        value: 0,
        category_id: 4,
        selected: false,
      },
    ],
    // breadcrumb
    breadcrumb: [
      {
        text: "dashboard",
        exact: true,
        to: "/",
      },
      {
        icon: "mdi-account-outline",
        text: "user_list",
        disabled: true,
        to: "/users",
      },
    ],

    // tab items
    tabItems: [
      {
        text: "all",
        icon: "fa-table",
        isSelected: 1,
        key: "all",
      },
      {
        text: "active",
        icon: "fa-thumbs-up",
        isSelected: 0,
        key: "active",
      },
      {
        text: "inactive",
        icon: "fa-ban",
        isSelected: 0,
        key: "inactive",
      },
      {
        text: "warning",
        icon: "fa-exclamation-triangle",
        isSelected: 0,
        key: "warning",
      },
      {
        text: "blocked",
        icon: "fa-times-circle",
        isSelected: 0,
        key: "blocked",
      },
      {
        text: "removed",
        icon: "fa-trash",
        isSelected: 0,
        key: "deleted",
      },
      {
        text: "pending",
        icon: "fa-user-slash",
        isSelected: 0,
        key: "pending",
      },
      {
        text: "tracing",
        icon: "fa-user-shield",
        isSelected: 0,
        key: "tracing",
      },
    ],

    // table headers
    headers: [
      {
        text: "id",
        value: "code",
        select: false,
        id: 1,
        category_id: 1,
        sortable: false,
      },
      {
        text: "profile",
        value: "image",
        select: false,
        id: 2,
        category_id: 1,
        sortable: false,
      },
      {
        text: "firstname",
        value: "firstname",
        select: false,
        id: 3,
        category_id: 1,
      },
      {
        text: "lastname",
        value: "lastname",
        select: false,
        id: 4,
        category_id: 1,
      },
      {
        text: "username",
        value: "username",
        select: false,
        id: 5,
        category_id: 1,
      },
      {
        text: "email",
        value: "email",
        select: false,
        id: 6,
        category_id: 1,
      },
      {
        text: "phone",
        value: "phone",
        select: false,
        id: 7,
        category_id: 1,
      },
      {
        text: "whatsapp",
        value: "whatsapp",
        select: false,
        id: 8,
        category_id: 1,
      },
      {
        text: "gender",
        value: "gender",
        select: false,
        id: 9,
        category_id: 1,
      },
      {
        text: "address",
        value: "address",
        select: false,
        id: 10,
        category_id: 3,
      },
      {
        text: "roles",
        value: "roles",
        select: false,
        id: 11,
        category_id: 2,
        sortable: false,
      },
      {
        text: "birth_date",
        value: "birth_date",
        select: false,
        id: 12,
        category_id: 4,
      },
      {
        text: "national",
        value: "country.national",
        select: false,
        id: 13,
        category_id: 1,
        sortable: false,
      },
      {
        text: "status",
        value: "status",
        select: false,
        id: 14,
        category_id: 2,
      },
      {
        text: "language",
        value: "language.name",
        select: false,
        id: 15,
        category_id: 1,
      },
      {
        text: "country",
        value: "country.name",
        select: false,
        id: 16,
        category_id: 3,
        sortable: false,
      },
      {
        text: "companies",
        value: "companies",
        select: false,
        id: 17,
        category_id: 2,
        sortable: false,
      },
      {
        text: "team",
        value: "teams",
        select: false,
        id: 18,
        category_id: 2,
        sortable: false,
      },
      {
        text: "state",
        value: "state.name",
        select: false,
        id: 19,
        category_id: 3,
        sortable: false,
      },
      {
        text: "tracing",
        value: "tracing_status",
        select: false,
        id: 20,
        category_id: 2,
      },
      {
        text: "current_country",
        value: "current_country.name",
        select: false,
        id: 21,
        category_id: 3,
        sortable: false,
      },
      {
        text: "title",
        value: "label.title",
        select: false,
        id: 22,
        category_id: 1,
        sortable: false,
      },
      {
        text: "note",
        value: "note",
        select: false,
        id: 23,
        category_id: 1,
      },
      {
        text: "created_by",
        value: "created_by",
        select: false,
        id: 24,
        category_id: 4,
      },
      {
        text: "created_at",
        value: "created_at",
        select: false,
        id: 25,
        category_id: 4,
      },
    ],

    // edit steppers
    editSteppers: [
      {
        icon: "fa-user",
        title: "general",
        slotName: "step1",
      },
      {
        icon: "fa-user",
        title: "account",
        slotName: "step2",
      },
      {
        icon: "fa-user",
        title: "personal",
        slotName: "step3",
      },
      {
        icon: "fa-user-shield",
        title: "permission",
        slotName: "step4",
      },
      {
        icon: "fa-comment-dots",
        title: "remarks",
        slotName: "step5",
      },
      {
        icon: "fa-thumbs-up",
        title: "done",
        slotName: "step6",
      },
    ],
    autoEditSteppers: [
      {
        icon: "fa-user",
        title: "general",
        slotName: "step1",
      },
      {
        icon: "fa-user",
        title: "account",
        slotName: "step2",
      },
      {
        icon: "fa-user",
        title: "personal",
        slotName: "step3",
      },
      {
        icon: "fa-user-shield",
        title: "permission",
        slotName: "step4",
      },
      {
        icon: "fa-comment-dots",
        title: "remarks",
        slotName: "step5",
      },
    ],
  };
}
